# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together=set([('email', 'cpf_cnpj')]),
        ),
    ]
